import{a as h,S as p,i}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const b="46839543-ea16205625b8d87bc87d9a951",L="https://pixabay.com/api/";async function w(r,t){try{return(await h.get(L,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(s){throw console.error("Помилка при отриманні зображень:",s),s}}function v(r){const{webformatURL:t,largeImageURL:s,tags:n,likes:e,views:o,comments:a,downloads:g}=r;return`
      <a href="${s}" class="gallery__item">
        <img src="${t}" alt="${n}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b>${e}</p>
          <p class="info-item"><b>Views</b>${o}</p>
          <p class="info-item"><b>Comments</b>${a}</p>
          <p class="info-item"><b>Downloads</b>${g}</p>
        </div>
      </a>
    `}function q(r){const t=document.querySelector(".gallery"),s=r.map(v).join("");t.insertAdjacentHTML("beforeend",s)}const S=document.querySelector("#search-form"),m=document.querySelector(".gallery"),c=document.querySelector(".load-more"),u=document.querySelector(".loader");let P=new p(".gallery a",{captionsData:"alt",captionDelay:250}),l=1,f="",d=0;S.addEventListener("submit",async r=>{r.preventDefault();const t=r.currentTarget.elements.searchQuery.value.trim();if(t===""){i.warning({title:"Warning",message:"Please enter a search query."});return}f=t,l=1,d=0,m.innerHTML="",c.classList.add("hidden"),await y()});c.addEventListener("click",async()=>{l+=1,await y()});async function y(){try{u.classList.remove("hidden");const{hits:r,total:t}=await w(f,l);if(d=t,r.length===0)i.info({title:"Information",message:"Sorry, no images match your search query. Please try again!"});else{q(r),P.refresh(),l*15<d?c.classList.remove("hidden"):(c.classList.add("hidden"),i.info({title:"Information",message:"We're sorry, but you've reached the end of search results."}));const{height:s}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{u.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
